---
- name: Add Repo File
  template: src=ubuntu.list.j2 dest=/etc/apt/sources.list.d/mariadb.list owner=root group=root mode=0644
  register: mariadb_list

- name: Add Repo Key
  apt_key: id=1BB943DB url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xCBCB082A1BB943DB state=present
  register: mariadb_key

- name: Update APT Cache
  apt: update_cache=yes
  when: mariadb_list.changed == True or mariadb_key.changed == True

- name: Install MariaDB
  apt: pkg={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb-client

- name: Start And Enable Service
  service: name=mysql state=started enabled=yes

- name: Install MySQLdb Python Package For Secure Installations
  apt: pkg=python-mysqldb state=present
  when: mysql_secure_installation and mysql_root_password is defined

- include: secure_install.yml
  when: mysql_secure_installation and mysql_root_password is defined