---
- name: Check If Composer Is Installed
  stat: "path=/usr/local/bin/composer"
  register: composer_bin

- name: Download Composer Installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: not composer_bin.stat.exists

- name: Run Composer Installer
  command: php composer-installer.php arg1
  args:
    chdir: /tmp
  when: not composer_bin.stat.exists

- name: Move Composer Into Global Location
  shell: mv /tmp/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  when: not composer_bin.stat.exists

- name: Update Composer To Latest Version
  shell: /usr/local/bin/composer self-update
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"

- name: Check If Prestissimo Is Installed In .composer
  stat: "path=~/.composer/vendor/hirak/prestissimo/composer.json"
  register: prestissimo_root_dir

- name: Check If Prestissimo Is Installed In .config/composer
  stat: "path=~/.config/composer/vendor/hirak/prestissimo/composer.json"
  register: prestissimo_config_dir

- name: Install Prestissimo If Needed
  shell: composer global require hirak/prestissimo
  when: not prestissimo_root_dir.stat.exists and not prestissimo_config_dir.stat.exists